import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:lucide_icons/lucide_icons.dart';
import 'package:provider/provider.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../constants/app_colors.dart';
import '../../models/course_models.dart';
import '../../models/active_recall_models.dart';
import '../../providers/auth_provider.dart';
import '../../services/gemini_ai_service.dart';
import '../../services/supabase_service.dart';
import '../../widgets/flashcard/flashcard_widget.dart';
import '../../widgets/flashcard/flashcard_result_widget.dart';
import '../modules/module_details_screen.dart';

class ActiveRecallSessionScreen extends StatefulWidget {
  final Course course;
  final Module module;

  const ActiveRecallSessionScreen({
    super.key,
    required this.course,
    required this.module,
  });

  @override
  State<ActiveRecallSessionScreen> createState() => _ActiveRecallSessionScreenState();
}

class _ActiveRecallSessionScreenState extends State<ActiveRecallSessionScreen> {
  late final GeminiAIService _geminiService;
  late final PageController _pageController;
  
  StudySessionStatus _currentStatus = StudySessionStatus.preparing;
  List<ActiveRecallFlashcard> _flashcards = [];
  Map<String, ActiveRecallAttempt> _preStudyAttempts = {};
  Map<String, ActiveRecallAttempt> _postStudyAttempts = {};
  
  int _currentFlashcardIndex = 0;
  bool _isLoading = true;
  String? _errorMessage;
  String? _sessionId;
  
  @override
  void initState() {
    super.initState();
    _geminiService = GeminiAIService();
    _pageController = PageController();
    _initializeSession();
  }

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  Future<void> _initializeSession() async {
    try {
      print('🚀 [ACTIVE RECALL] Starting session initialization');
      setState(() {
        _isLoading = true;
        _errorMessage = null;
      });

      // Session ID will be generated by database
      
      // Check for PDF materials and show appropriate loading message
      final pdfMaterials = widget.module.materials.where((m) => m.fileType.toLowerCase() == 'pdf').length;
      if (pdfMaterials > 0) {
        print('📄 [ACTIVE RECALL] Found $pdfMaterials PDF material(s), extracting content for better flashcards...');
        setState(() {
          _errorMessage = 'Analyzing PDF content to create better study questions...\nThis may take a moment.';
        });
      }
      
      // Generate flashcards from module materials (now with PDF content extraction)
      print('🧠 [ACTIVE RECALL] Generating flashcards for ${widget.module.materials.length} materials');
      final flashcards = await _geminiService.generateFlashcardsFromMaterials(
        widget.module.materials,
        widget.module.title,
      );

      if (flashcards.isEmpty) {
        throw Exception('No flashcards could be generated from the materials');
      }

      // Save session to database
      await _createSessionInDatabase();
      
      // Save flashcards to database
      await _saveFlashcardsToDatabase(flashcards);

      setState(() {
        _flashcards = flashcards;
        _currentStatus = StudySessionStatus.preStudy;
        _isLoading = false;
        _errorMessage = null; // Clear any loading messages
      });

      print('✅ [ACTIVE RECALL] Session initialized with ${flashcards.length} flashcards');

    } catch (e) {
      print('❌ [ACTIVE RECALL] Session initialization failed: $e');
      setState(() {
        _errorMessage = 'Failed to generate study materials: $e';
        _isLoading = false;
      });
    }
  }

  void _handleAnswerSubmitted(String answer, int responseTimeMs) {
    final flashcard = _flashcards[_currentFlashcardIndex];
    final isCorrect = _evaluateAnswer(answer, flashcard.answer);
    final phase = _currentStatus == StudySessionStatus.preStudy ? 'PRE-STUDY' : 'POST-STUDY';
    
    print('🎯 [ACTIVE RECALL - $phase] Answer submitted for flashcard ${_currentFlashcardIndex + 1}/${_flashcards.length}');
    print('   Question: ${flashcard.question}');
    print('   User Answer: "$answer"');
    print('   Correct Answer: "${flashcard.answer}"');
    print('   Result: ${isCorrect ? '✅ CORRECT' : '❌ INCORRECT'}');
    print('   Response Time: ${(responseTimeMs / 1000).toStringAsFixed(1)}s');
    
    final attempt = ActiveRecallAttempt(
      id: '${_sessionId}_${flashcard.id}_${_currentStatus == StudySessionStatus.preStudy ? 'pre' : 'post'}',
      sessionId: _sessionId!,
      flashcardId: flashcard.id,
      userAnswer: answer,
      isCorrect: isCorrect,
      responseTimeSeconds: (responseTimeMs / 1000).round(),
      attemptedAt: DateTime.now(),
      isPreStudy: _currentStatus == StudySessionStatus.preStudy,
    );

    if (_currentStatus == StudySessionStatus.preStudy) {
      _preStudyAttempts[flashcard.id] = attempt;
      final preCorrect = _preStudyAttempts.values.where((a) => a.isCorrect).length;
      print('📊 [PRE-STUDY PROGRESS] $preCorrect/${_preStudyAttempts.length} correct so far');
    } else {
      _postStudyAttempts[flashcard.id] = attempt;
      final postCorrect = _postStudyAttempts.values.where((a) => a.isCorrect).length;
      print('📊 [POST-STUDY PROGRESS] $postCorrect/${_postStudyAttempts.length} correct so far');
    }

    // Save attempt to database
    _saveAttemptToDatabase(attempt);

    // Show result screen
    _showResultDialog(flashcard, answer, isCorrect, responseTimeMs);
  }

  bool _evaluateAnswer(String userAnswer, String correctAnswer) {
    // Simple evaluation - in a real app, you might use more sophisticated matching
    final userLower = userAnswer.toLowerCase().trim();
    final correctLower = correctAnswer.toLowerCase().trim();
    
    // Check for exact match
    if (userLower == correctLower) return true;
    
    // Check if user answer contains key words from correct answer
    final correctWords = correctLower.split(' ').where((w) => w.length > 3).toList();
    final userWords = userLower.split(' ');
    
    int matches = 0;
    for (final word in correctWords) {
      if (userWords.any((uw) => uw.contains(word) || word.contains(uw))) {
        matches++;
      }
    }
    
    // Consider correct if at least 60% of key words match
    return correctWords.isNotEmpty && (matches / correctWords.length) >= 0.6;
  }

  void _showResultDialog(
    ActiveRecallFlashcard flashcard,
    String userAnswer,
    bool isCorrect,
    int responseTimeMs,
  ) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => Dialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        child: FlashcardResultWidget(
          flashcard: flashcard,
          userAnswer: userAnswer,
          isCorrect: isCorrect,
          responseTimeMs: responseTimeMs,
          onContinue: () {
            Navigator.of(context).pop();
            _moveToNextFlashcard();
          },
        ),
      ),
    );
  }

  void _moveToNextFlashcard() {
    if (_currentFlashcardIndex < _flashcards.length - 1) {
      setState(() {
        _currentFlashcardIndex++;
      });
      
      // Safely navigate to next page
      if (_pageController.hasClients && _pageController.positions.isNotEmpty) {
        _pageController.nextPage(
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeInOut,
        );
      } else {
        print('⚠️ [ACTIVE RECALL] PageController not ready for nextPage');
      }
    } else {
      _completeCurrentPhase();
    }
  }

  void _completeCurrentPhase() {
    if (_currentStatus == StudySessionStatus.preStudy) {
      // Move to study phase
      setState(() {
        _currentStatus = StudySessionStatus.studying;
      });
      _showStudyMaterialsScreen();
    } else if (_currentStatus == StudySessionStatus.postStudy) {
      // Complete session
      setState(() {
        _currentStatus = StudySessionStatus.completed;
      });
      _showSessionResults();
    }
  }

  void _showStudyMaterialsScreen() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (context) {
        final screenHeight = MediaQuery.of(context).size.height;
        final topPadding = MediaQuery.of(context).padding.top;
        final bottomPadding = MediaQuery.of(context).padding.bottom;
        final keyboardHeight = MediaQuery.of(context).viewInsets.bottom;
        final maxHeight = screenHeight - topPadding - bottomPadding - keyboardHeight - 100; // 100px margin from top
        
        return SafeArea(
          child: ConstrainedBox(
            constraints: BoxConstraints(
              maxHeight: maxHeight,
              minHeight: 400,
            ),
            child: Container(
              decoration: const BoxDecoration(
                color: AppColors.white,
                borderRadius: BorderRadius.only(
                  topLeft: Radius.circular(20),
                  topRight: Radius.circular(20),
                ),
              ),
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
            // Header
            Container(
              padding: const EdgeInsets.all(20),
              child: Column(
                children: [
                  Container(
                    width: 40,
                    height: 4,
                    decoration: BoxDecoration(
                      color: AppColors.grey300,
                      borderRadius: BorderRadius.circular(2),
                    ),
                  ),
                  const SizedBox(height: 16),
                  Text(
                    'Study Materials',
                    style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'Review the materials, then test your memory again',
                    style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                      color: AppColors.textSecondary,
                    ),
                    textAlign: TextAlign.center,
                  ),
                ],
              ),
            ),
            
            // Materials list
            Flexible(
              child: ListView.builder(
                padding: const EdgeInsets.symmetric(horizontal: 20),
                itemCount: widget.module.materials.length,
                itemBuilder: (context, index) {
                  final material = widget.module.materials[index];
                  return _buildMaterialCard(material);
                },
              ),
            ),
            
            // Continue button
            Container(
              padding: EdgeInsets.only(
                left: 20,
                right: 20,
                top: 16,
                bottom: 20 + MediaQuery.of(context).padding.bottom,
              ),
              child: SizedBox(
                width: double.infinity,
                height: 56,
                child: ElevatedButton(
                  onPressed: () {
                    Navigator.of(context).pop();
                    _startPostStudyPhase();
                  },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.green,
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: const Text(
                    'Ready for Memory Test',
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ),
            ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }

  Widget _buildMaterialCard(CourseMaterial material) {
    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      child: InkWell(
        onTap: () => _openMaterial(material),
        borderRadius: BorderRadius.circular(12),
        child: Container(
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            color: AppColors.white,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: AppColors.grey200),
            boxShadow: [
              BoxShadow(
                color: Colors.black.withOpacity(0.05),
                blurRadius: 8,
                offset: const Offset(0, 2),
              ),
            ],
          ),
          child: Row(
            children: [
              Container(
                width: 48,
                height: 48,
                decoration: BoxDecoration(
                  color: Colors.blue.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: const Icon(
                  LucideIcons.fileText,
                  color: Colors.blue,
                  size: 24,
                ),
              ),
              const SizedBox(width: 16),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      material.title,
                      style: const TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w600,
                        color: AppColors.textPrimary,
                      ),
                    ),
                    if (material.description != null) ...[
                      const SizedBox(height: 4),
                      Text(
                        material.description!,
                        style: const TextStyle(
                          fontSize: 14,
                          color: AppColors.textSecondary,
                        ),
                        maxLines: 2,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ],
                  ],
                ),
              ),
              const Icon(
                LucideIcons.externalLink,
                color: AppColors.textSecondary,
                size: 16,
              ),
            ],
          ),
        ),
      ),
    );
  }

  void _openMaterial(CourseMaterial material) async {
    try {
      print('🔗 [URL LAUNCHER] Attempting to open: ${material.fileUrl}');
      print('📄 [FILE INFO] Type: ${material.fileType}, Name: ${material.fileName}');
      
      final Uri url = Uri.parse(material.fileUrl);
      
      // Show loading indicator
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Row(
              children: [
                const SizedBox(
                  width: 16,
                  height: 16,
                  child: CircularProgressIndicator(
                    strokeWidth: 2,
                    valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                  ),
                ),
                const SizedBox(width: 12),
                Text('Opening ${material.fileName}...'),
              ],
            ),
            duration: const Duration(seconds: 2),
            backgroundColor: Colors.blue,
          ),
        );
      }
      
      // Try different launch modes for better compatibility
      bool launched = false;
      String? lastError;
      
      // Check if URL can be launched first
      bool canLaunch = await canLaunchUrl(url);
      print('🔍 [URL LAUNCHER] canLaunchUrl result: $canLaunch');
      
      if (!canLaunch) {
        print('⚠️ [URL LAUNCHER] canLaunchUrl returned false, but trying anyway...');
      }
      
      // First try: Platform default (recommended approach)
      try {
        await launchUrl(url, mode: LaunchMode.platformDefault);
        launched = true;
        print('✅ [URL LAUNCHER] Successfully launched with platformDefault mode');
      } catch (e) {
        lastError = e.toString();
        print('⚠️ [URL LAUNCHER] platformDefault mode failed: $e');
      }
      
      // Second try: External application (for PDFs, this opens in default PDF viewer)
      if (!launched) {
        try {
          await launchUrl(url, mode: LaunchMode.externalApplication);
          launched = true;
          print('✅ [URL LAUNCHER] Successfully launched with externalApplication mode');
        } catch (e) {
          lastError = e.toString();
          print('⚠️ [URL LAUNCHER] externalApplication mode failed: $e');
        }
      }
      
      // Third try: In-app web view (fallback)
      if (!launched) {
        try {
          await launchUrl(url, mode: LaunchMode.inAppWebView);
          launched = true;
          print('✅ [URL LAUNCHER] Successfully launched with inAppWebView mode');
        } catch (e) {
          lastError = e.toString();
          print('⚠️ [URL LAUNCHER] inAppWebView mode failed: $e');
        }
      }
      
      if (!launched) {
        print('❌ [URL LAUNCHER] All launch attempts failed. Last error: $lastError');
        if (mounted) {
          ScaffoldMessenger.of(context).hideCurrentSnackBar();
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('Could not open ${material.fileName}'),
                  const SizedBox(height: 4),
                  Text(
                    'No app found to handle PDF files. Please install a PDF reader.',
                    style: TextStyle(fontSize: 12, color: Colors.white.withOpacity(0.8)),
                  ),
                ],
              ),
              backgroundColor: Colors.red,
              duration: const Duration(seconds: 5),
              action: SnackBarAction(
                label: 'Copy URL',
                textColor: Colors.white,
                onPressed: () async {
                  await Clipboard.setData(ClipboardData(text: material.fileUrl));
                  if (mounted) {
                    ScaffoldMessenger.of(context).hideCurrentSnackBar();
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(
                        content: Text('URL copied to clipboard!'),
                        backgroundColor: Colors.green,
                        duration: Duration(seconds: 2),
                      ),
                    );
                  }
                },
              ),
            ),
          );
        }
      } else {
        // Hide loading indicator on success
        if (mounted) {
          ScaffoldMessenger.of(context).hideCurrentSnackBar();
        }
      }
      
    } catch (e) {
      print('❌ [URL LAUNCHER ERROR] Exception: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).hideCurrentSnackBar();
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Error opening ${material.fileName}'),
                const SizedBox(height: 4),
                Text(
                  e.toString(),
                  style: TextStyle(fontSize: 12, color: Colors.white.withOpacity(0.8)),
                ),
              ],
            ),
            backgroundColor: Colors.red,
            duration: const Duration(seconds: 5),
            action: SnackBarAction(
              label: 'Copy URL',
              textColor: Colors.white,
              onPressed: () async {
                await Clipboard.setData(ClipboardData(text: material.fileUrl));
                if (mounted) {
                  ScaffoldMessenger.of(context).hideCurrentSnackBar();
                  ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(
                      content: Text('URL copied to clipboard!'),
                      backgroundColor: Colors.green,
                      duration: Duration(seconds: 2),
                    ),
                  );
                }
              },
            ),
          ),
        );
      }
    }
  }

  void _startPostStudyPhase() {
    setState(() {
      _currentStatus = StudySessionStatus.postStudy;
      _currentFlashcardIndex = 0;
    });
    
    // Wait for PageView to be built and PageController to be attached
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_pageController.hasClients && _pageController.positions.isNotEmpty) {
        _pageController.animateToPage(
          0,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeInOut,
        );
      } else {
        // If PageController isn't ready, just jump to page 0 without animation
        print('⚠️ [ACTIVE RECALL] PageController not ready, using jumpToPage instead');
        if (_pageController.hasClients) {
          _pageController.jumpToPage(0);
        }
      }
    });
  }

  void _showSessionResults() {
    print('🏁 [SESSION COMPLETE] Calculating results...');
    print('📊 [DEBUG] Pre-study attempts: ${_preStudyAttempts.length}');
    print('📊 [DEBUG] Post-study attempts: ${_postStudyAttempts.length}');
    
    // Debug pre-study results
    final preCorrect = _preStudyAttempts.values.where((a) => a.isCorrect).length;
    print('📊 [PRE-STUDY FINAL] $preCorrect/${_preStudyAttempts.length} correct');
    
    // Debug post-study results  
    final postCorrect = _postStudyAttempts.values.where((a) => a.isCorrect).length;
    print('📊 [POST-STUDY FINAL] $postCorrect/${_postStudyAttempts.length} correct');
    
    final results = StudySessionResults.calculate(
      _flashcards,
      [..._preStudyAttempts.values, ..._postStudyAttempts.values],
    );
    
    print('📈 [RESULTS] Improvement: ${results.improvementPercentage.toStringAsFixed(1)}%');
    print('⏱️ [RESULTS] Avg response time: ${results.averageResponseTime}s');

    // Update session as completed in database
    _updateSessionStatus(StudySessionStatus.completed);

    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => Dialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        child: _buildResultsDialog(results),
      ),
    );
  }

  Widget _buildResultsDialog(StudySessionResults results) {
    return Container(
      padding: const EdgeInsets.all(24),
      child: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // Header
            Container(
              width: 80,
              height: 80,
              decoration: BoxDecoration(
                color: results.improvementPercentage > 0 
                    ? Colors.green.withOpacity(0.1)
                    : Colors.blue.withOpacity(0.1),
                shape: BoxShape.circle,
              ),
              child: Icon(
                results.improvementPercentage > 0 
                    ? LucideIcons.trendingUp
                    : LucideIcons.brain,
                color: results.improvementPercentage > 0 
                    ? Colors.green
                    : Colors.blue,
                size: 40,
              ),
            ),
            
            const SizedBox(height: 16),
            
            Text(
              'Session Complete!',
              style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),
            
            const SizedBox(height: 24),
            
            // Results stats
            Row(
              children: [
                Expanded(
                  child: _buildStatCard(
                    'Pre-Study',
                    '${results.preStudyCorrect}/${results.totalFlashcards}',
                    Colors.orange,
                  ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: _buildStatCard(
                    'Post-Study',
                    '${results.postStudyCorrect}/${results.totalFlashcards}',
                    Colors.green,
                  ),
                ),
              ],
            ),
            
            const SizedBox(height: 16),
            
            _buildStatCard(
              'Improvement',
              results.improvementPercentage > 0 
                  ? '+${results.improvementPercentage.toStringAsFixed(1)}%'
                  : '${results.improvementPercentage.toStringAsFixed(1)}%',
              results.improvementPercentage > 0 ? Colors.green : Colors.red,
            ),
            
            const SizedBox(height: 32),
            
            // Action buttons
            Row(
              children: [
                Expanded(
                  child: ElevatedButton(
                    onPressed: () {
                      Navigator.of(context).pop(); // Close dialog
                      Navigator.of(context).pop(); // Go back to module details
                    },
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.grey[100],
                      foregroundColor: AppColors.textPrimary,
                      elevation: 0,
                      padding: const EdgeInsets.symmetric(vertical: 16),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                        side: BorderSide(color: Colors.grey[300]!),
                      ),
                    ),
                    child: const Text(
                      'Done',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: ElevatedButton(
                    onPressed: () {
                      Navigator.of(context).pop(); // Close dialog
                      _initializeSession(); // Restart session
                    },
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.bgPrimary,
                      foregroundColor: Colors.white,
                      elevation: 2,
                      padding: const EdgeInsets.symmetric(vertical: 16),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                    ),
                    child: const Text(
                      'Study Again',
                      style: TextStyle(
                        fontSize: 16,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildStatCard(String label, String value, Color color) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: color.withOpacity(0.3)),
      ),
      child: Column(
        children: [
          Text(
            value,
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              color: color,
            ),
          ),
          const SizedBox(height: 4),
          Text(
            label,
            style: TextStyle(
              fontSize: 12,
              color: color,
              fontWeight: FontWeight.w500,
            ),
          ),
        ],
      ),
    );
  }

  String _getPhaseTitle() {
    switch (_currentStatus) {
      case StudySessionStatus.preparing:
        return 'Preparing Session...';
      case StudySessionStatus.preStudy:
        return 'Pre-Study Test';
      case StudySessionStatus.studying:
        return 'Study Materials';
      case StudySessionStatus.postStudy:
        return 'Memory Test';
      case StudySessionStatus.completed:
        return 'Session Complete';
      case StudySessionStatus.paused:
        return 'Session Paused';
    }
  }

  String _getPhaseDescription() {
    switch (_currentStatus) {
      case StudySessionStatus.preparing:
        return 'Generating flashcards from your materials...';
      case StudySessionStatus.preStudy:
        return 'Test your existing knowledge before studying';
      case StudySessionStatus.studying:
        return 'Review the materials carefully';
      case StudySessionStatus.postStudy:
        return 'Test your memory after studying';
      case StudySessionStatus.completed:
        return 'Great work! Review your results below';
      case StudySessionStatus.paused:
        return 'Session is paused';
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.bgSecondary,
      appBar: AppBar(
        title: Text(_getPhaseTitle()),
        backgroundColor: AppColors.bgSecondary,
        foregroundColor: AppColors.textPrimary,
        elevation: 0,
        actions: [
          if (_currentStatus == StudySessionStatus.preStudy || 
              _currentStatus == StudySessionStatus.postStudy)
            Padding(
              padding: const EdgeInsets.only(right: 16),
              child: Center(
                child: Text(
                  '${_currentFlashcardIndex + 1}/${_flashcards.length}',
                  style: const TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
            ),
        ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : _errorMessage != null
              ? _buildErrorScreen()
              : _buildSessionContent(),
    );
  }

  Widget _buildErrorScreen() {
    // Check if this is actually a loading message rather than an error
    final isLoadingMessage = _errorMessage?.contains('Analyzing PDF content') == true;
    
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              isLoadingMessage ? LucideIcons.fileText : LucideIcons.alertTriangle,
              size: 64,
              color: isLoadingMessage ? Colors.blue : Colors.red,
            ),
            const SizedBox(height: 16),
            Text(
              isLoadingMessage ? 'Processing Materials' : 'Session Error',
              style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              _errorMessage!,
              textAlign: TextAlign.center,
              style: const TextStyle(color: AppColors.textSecondary),
            ),
            if (isLoadingMessage) ...[
              const SizedBox(height: 24),
              const CircularProgressIndicator(),
              const SizedBox(height: 16),
              const Text(
                'Extracting text from PDF materials to generate\nhigh-quality, content-specific study questions',
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: 12,
                  color: AppColors.textSecondary,
                ),
              ),
            ] else ...[
              const SizedBox(height: 24),
              ElevatedButton(
                onPressed: _initializeSession,
                child: const Text('Retry'),
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildSessionContent() {
    if (_currentStatus == StudySessionStatus.preStudy || 
        _currentStatus == StudySessionStatus.postStudy) {
      return Column(
        children: [
          // Progress indicator
          Container(
            padding: const EdgeInsets.all(16),
            child: Column(
              children: [
                Text(
                  _getPhaseDescription(),
                  style: const TextStyle(
                    fontSize: 16,
                    color: AppColors.textSecondary,
                  ),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 16),
                LinearProgressIndicator(
                  value: (_currentFlashcardIndex + 1) / _flashcards.length,
                  backgroundColor: Colors.grey[300],
                  valueColor: AlwaysStoppedAnimation<Color>(
                    _currentStatus == StudySessionStatus.preStudy 
                        ? Colors.orange 
                        : Colors.green,
                  ),
                ),
              ],
            ),
          ),
          
          // Flashcard content
          Expanded(
            child: PageView.builder(
              controller: _pageController,
              physics: const NeverScrollableScrollPhysics(),
              itemCount: _flashcards.length,
              itemBuilder: (context, index) {
                return FlashcardWidget(
                  flashcard: _flashcards[index],
                  onAnswerSubmitted: _handleAnswerSubmitted,
                  isPreStudy: _currentStatus == StudySessionStatus.preStudy,
                  onShowHint: () {
                    // Track hint usage if needed
                  },
                );
              },
            ),
          ),
        ],
      );
    }

    return const Center(
      child: Text('Invalid session state'),
    );
  }

  // Database persistence methods
  Future<void> _createSessionInDatabase() async {
    try {
      print('💾 [DATABASE] Creating session in database...');
      
      // Get authenticated user
      final authProvider = Provider.of<AuthProvider>(context, listen: false);
      final currentUser = authProvider.currentUser;
      
      if (currentUser == null) {
        throw Exception('User not authenticated. Please log in to start study session.');
      }
      
      final userId = currentUser.id;
      print('💾 [DATABASE] Using authenticated user: ${currentUser.name} (${currentUser.email})');
      print('💾 [DATABASE] User ID: $userId');
      
      // Validate module exists
      final moduleExists = await _validateModuleExists(widget.module.id);
      if (!moduleExists) {
        throw Exception('Module ${widget.module.id} does not exist in database');
      }
      
      // Validate user exists in database (should exist since they're authenticated)
      final userExists = await _validateUserExists(userId);
      if (!userExists) {
        throw Exception('Authenticated user $userId not found in database');
      }
      
      final sessionData = {
        // Don't include 'id' - let database generate UUID
        'user_id': userId,
        'module_id': widget.module.id,
        'status': StudySessionStatus.preparing.name,
        'session_data': {
          'course_title': widget.course.title,
          'module_title': widget.module.title,
          'total_materials': widget.module.materials.length,
        },
      };
      
      print('💾 [DATABASE] Session data: $sessionData');
      
      final response = await SupabaseService.client
          .from('active_recall_sessions')
          .insert(sessionData)
          .select('id')
          .single();
      
      // Store the generated session ID
      _sessionId = response['id'];
      print('✅ [DATABASE] Session created successfully with ID: $_sessionId');
    } catch (e) {
      print('❌ [DATABASE] Failed to create session: $e');
      
      // Provide specific error messages
      if (e.toString().contains('User not authenticated')) {
        print('💡 [AUTH] Error: User not logged in. Redirect to login screen.');
        // In a real app, you'd navigate to login screen here
        _sessionId = null;
        setState(() {
          _errorMessage = 'Please log in to start a study session';
          _isLoading = false;
        });
        return;
      } else if (e.toString().contains('active_recall_sessions_user_id_fkey')) {
        print('💡 [DATABASE] Error: Authenticated user ID not found in users table.');
      } else if (e.toString().contains('active_recall_sessions_module_id_fkey')) {
        print('💡 [DATABASE] Error: Module ID does not exist. Check modules table.');
      }
      
      // Generate fallback session ID for local tracking
      _sessionId = 'local_${DateTime.now().millisecondsSinceEpoch}';
      print('⚠️ [DATABASE] Using fallback session ID: $_sessionId');
    }
  }

  Future<void> _saveFlashcardsToDatabase(List<ActiveRecallFlashcard> flashcards) async {
    try {
      print('💾 [DATABASE] Saving ${flashcards.length} flashcards...');
      print('💾 [DATABASE] Module ID: ${widget.module.id}');
      
      // Validate all material IDs exist before saving flashcards
      for (final flashcard in flashcards) {
        final materialExists = await _validateMaterialExists(flashcard.materialId);
        if (!materialExists) {
          print('⚠️ [DATABASE] Material ${flashcard.materialId} does not exist, skipping flashcard ${flashcard.id}');
          continue;
        }
      }
      
      final flashcardData = flashcards.map((flashcard) {
        final json = flashcard.toJson();
        print('💾 [DATABASE] Flashcard: ${json['id']} for material ${json['material_id']}');
        return json;
      }).toList();
      
      // Insert flashcards in batches to handle large sets
      const batchSize = 10;
      for (int i = 0; i < flashcardData.length; i += batchSize) {
        final batch = flashcardData.skip(i).take(batchSize).toList();
        await SupabaseService.client
            .from('active_recall_flashcards')
            .insert(batch);
        print('💾 [DATABASE] Saved batch ${(i ~/ batchSize) + 1} of ${(flashcardData.length / batchSize).ceil()}');
      }
      
      print('✅ [DATABASE] All flashcards saved successfully');
    } catch (e) {
      print('❌ [DATABASE] Failed to save flashcards: $e');
      
      // Provide specific error messages
      if (e.toString().contains('duplicate key')) {
        print('💡 [DATABASE] Error: Duplicate flashcard IDs detected. Check ID generation logic.');
      } else if (e.toString().contains('active_recall_flashcards_material_id_fkey')) {
        print('💡 [DATABASE] Error: Material ID does not exist. Check course_materials table.');
      } else if (e.toString().contains('active_recall_flashcards_module_id_fkey')) {
        print('💡 [DATABASE] Error: Module ID does not exist. Check modules table.');
      } else if (e.toString().contains('row-level security policy')) {
        print('⚠️ [DATABASE] RLS policy blocked flashcard insert - user may not be enrolled in course');
      }
      
      // Don't throw - continue with local flashcards
    }
  }

  Future<void> _saveAttemptToDatabase(ActiveRecallAttempt attempt) async {
    try {
      print('💾 [DATABASE] Saving attempt: ${attempt.isCorrect ? 'CORRECT' : 'INCORRECT'} - ${attempt.isPreStudy ? 'PRE' : 'POST'}');
      print('💾 [DATABASE] Session ID: ${attempt.sessionId}');
      print('💾 [DATABASE] Flashcard ID: ${attempt.flashcardId}');
      
      final attemptData = attempt.toJson();
      // Remove the 'id' field - let database generate it
      attemptData.remove('id');
      
      await SupabaseService.client
          .from('active_recall_attempts')
          .insert(attemptData);
      
      print('✅ [DATABASE] Attempt saved successfully');
    } catch (e) {
      print('❌ [DATABASE] Failed to save attempt: $e');
      if (e.toString().contains('row-level security policy')) {
        print('⚠️ [DATABASE] RLS policy blocked attempt insert - session may not belong to user');
      }
      // Don't throw - continue with local tracking
    }
  }

  Future<void> _updateSessionStatus(StudySessionStatus status) async {
    if (_sessionId == null || _sessionId!.startsWith('local_')) {
      print('⚠️ [DATABASE] Skipping session status update - using local session ID');
      return;
    }
    
    try {
      print('💾 [DATABASE] Updating session status to: ${status.name}');
      print('💾 [DATABASE] Session ID: $_sessionId');
      
      final updateData = <String, dynamic>{
        'status': status.name,
      };
      
      if (status == StudySessionStatus.completed) {
        updateData['completed_at'] = DateTime.now().toIso8601String();
      }
      
      await SupabaseService.client
          .from('active_recall_sessions')
          .update(updateData)
          .eq('id', _sessionId!);
      
      print('✅ [DATABASE] Session status updated successfully');
    } catch (e) {
      print('❌ [DATABASE] Failed to update session status: $e');
      if (e.toString().contains('row-level security policy')) {
        print('⚠️ [DATABASE] RLS policy blocked session update - session may not belong to user');
      }
    }
  }

  // Database validation methods
  Future<bool> _validateUserExists(String userId) async {
    try {
      final response = await SupabaseService.client
          .from('users')
          .select('id')
          .eq('id', userId)
          .maybeSingle();
      
      final exists = response != null;
      print('🔍 [DATABASE] User $userId exists: $exists');
      return exists;
    } catch (e) {
      print('❌ [DATABASE] Error checking user existence: $e');
      return false;
    }
  }

  Future<bool> _validateModuleExists(String moduleId) async {
    try {
      final response = await SupabaseService.client
          .from('modules')
          .select('id')
          .eq('id', moduleId)
          .maybeSingle();
      
      final exists = response != null;
      print('🔍 [DATABASE] Module $moduleId exists: $exists');
      return exists;
    } catch (e) {
      print('❌ [DATABASE] Error checking module existence: $e');
      return false;
    }
  }

  Future<bool> _validateMaterialExists(String materialId) async {
    try {
      final response = await SupabaseService.client
          .from('course_materials')
          .select('id')
          .eq('id', materialId)
          .maybeSingle();
      
      final exists = response != null;
      print('🔍 [DATABASE] Material $materialId exists: $exists');
      return exists;
    } catch (e) {
      print('❌ [DATABASE] Error checking material existence: $e');
      return false;
    }
  }
}